name: flutter_password_strength_validator
description: A Flutter package to validate password strength.
version: 1.0.1 
homepage: https://github.com/victorpadovam/flutter_password_strength_validator  
repository: https://github.com/victorpadovam/flutter_password_strength_validator 

environment:
  sdk: ">=2.12.0 <4.0.0"  # Suporta Dart 2.12 até o último Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  validators: ^3.0.0  
  flutter_secure_storage: ^5.0.2  
  intl: ^0.18.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

example: example/main.dart 

# Licença do seu pacote (opcional, você pode escolher a licença que desejar)
license: MIT
